// src/pages/Dashboard.jsx
import React, { useState } from 'react';
import { useInView } from 'react-intersection-observer';
import Card from '../components/Card';
import Navigation from '../components/Navigation';
import HeroSection from '../components/HeroSection';
import ProjectCard from '../components/ProjectCard';
import ContactForm from '../components/ContactForm';


const Dashboard = () => {
  const currentYear = new Date().getFullYear();
  const [showAllProjects, setShowAllProjects] = useState(false);

  // Social links data
  const socialLinks = [
    { href: 'https://www.facebook.com/TheSujayHalder', icon: 'pi-facebook', label: 'Facebook' },
    { href: 'https://twitter.com/TheSujayHalder', icon: 'pi-twitter', label: 'Twitter' },
    { href: 'https://www.instagram.com/the_sujay_halder', icon: 'pi-instagram', label: 'Instagram' },
    { href: 'https://www.linkedin.com/in/sujayhalder', icon: 'pi-linkedin', label: 'LinkedIn' },
    { href: 'https://github.com/know120', icon: 'pi-github', label: 'GitHub' }
  ];

  // Intersection Observer for animations
  const [aboutRef, aboutInView] = useInView({ threshold: 0.3, triggerOnce: true });
  const [projectsRef, projectsInView] = useInView({ threshold: 0.3, triggerOnce: true });
  const [blogRef, blogInView] = useInView({ threshold: 0.3, triggerOnce: true });
  const [contactRef, contactInView] = useInView({ threshold: 0.3, triggerOnce: true });

  const expASL = {
    header: 'Alumnus Software Limited',
    title: 'Full Stack Developer',
    body: 'Developed a web application for one of the leading Tire manufacturing company using Angular 7,Bootstrap 5, .NET Framework, and SQLServer.',
    footer: 'July 2022 - Present'
  };

  const expDSS = {
    header: 'Divsoft Software Solutions',
    title: 'Software Engineer',
    body: 'Developed a Over Speed Detection System using CPP and OpenCV. That can receive the speed of the vehicle from a remote server using TCP Connection and Capture the image of vehicle.',
    footer: 'August 2021 - July 2022'
  };

  // Enhanced project data
  const projects = [
    {
      title: 'Political Spending Analysis',
      description: 'Comprehensive analysis and visualization of political advertising spending on Facebook using Python and data visualization.',
      technologies: ['Python', 'Pandas', 'Matplotlib', 'Seaborn', 'Jupyter'],
      image: 'https://via.placeholder.com/400x200/6366f1/ffffff?text=Data+Analysis',
      liveDemo: 'https://jovian.ai/know120/fb-ad-lib',
      github: 'https://github.com/know120/political-spending-analysis',
      features: ['Interactive visualizations', 'Statistical analysis', 'Trend identification', 'Automated reports'],
      duration: '3 months',
      teamSize: 'Solo Project'
    },
    {
      title: 'COVID-19 X-Ray Classifier',
      description: 'Machine learning model for COVID-19 detection using chest X-ray images with deep learning techniques.',
      technologies: ['Python', 'TensorFlow', 'OpenCV', 'Keras', 'NumPy'],
      image: 'https://via.placeholder.com/400x200/8b5cf6/ffffff?text=ML+Project',
      liveDemo: 'https://know120.github.io/covid-xray-classifier',
      github: 'https://github.com/know120/covid-xray-ml',
      features: ['Deep learning CNN', '95% accuracy rate', 'Real-time processing', 'Web interface'],
      duration: '6 months',
      teamSize: '4 developers'
    },
    {
      title: 'Budget Evaluation System',
      description: 'Full-stack web application for budget management built with Angular, .NET Framework, and SQL Server.',
      technologies: ['Angular 7', 'TypeScript', '.NET Framework', 'SQL Server', 'Bootstrap'],
      image: 'https://via.placeholder.com/400x200/a855f7/ffffff?text=Budget+System',
      features: ['Budget tracking', 'Financial reports', 'User management', 'Dashboard analytics'],
      duration: '8 months',
      teamSize: '2 developers'
    },
    {
      title: 'Speed Detection System',
      description: 'Over-speed detection system using C++ and OpenCV with TCP connection for real-time vehicle monitoring.',
      technologies: ['C++', 'OpenCV', 'TCP/IP', 'Computer Vision'],
      image: 'https://via.placeholder.com/400x200/06b6d4/ffffff?text=Speed+Detection',
      liveDemo: null,
      github: 'https://github.com/know120/speed-detection-system',
      features: [
        'Real-time speed calculation',
        'Automatic image capture',
        'TCP server communication',
        'Alert system integration'
      ],
      duration: '6 months',
      teamSize: '3 developers'
    }
  ];

  return (
    <div className="app mx-5">
      <Navigation />

      {/* Enhanced Hero Section */}
      <HeroSection />

      {/* Skills Section */}
      {/* <SkillsSection /> */}

      {/* Enhanced About/Experience Section */}
      <section id="about" className="h-screen" ref={aboutRef}>
        <h1 className="text-4xl text-center mb-5">Work Experience</h1>
        <div className='flex flex-col md:flex-row items-center justify-content gap-5'>
          <div className="w-full md:w-1/2">
            <Card
              header={expASL.header}
              title={expASL.title}
              body={expASL.body}
              footer={expASL.footer}
            />
          </div>
          <div className="w-full md:w-1/2">
            <Card
              header={expDSS.header}
              title={expDSS.title}
              body={expDSS.body}
              footer={expDSS.footer}
            />
          </div>
        </div>
      </section>

      {/* Projects Section */}
      <section id="projects" className={`h-screen bg-blue-950`} ref={projectsRef}>
        <div className="grid grid-cols-2 grid-rows-2 gap-2 items-center justify-center">
          {projects.length > 0 ? (
            projects.map((project, index) => (
              <ProjectCard key={`project-${index}`} project={project} />
            ))
          ) : (
            <div className="w-100 text-center">
              <p className="text-white">No projects found</p>
            </div>
          )}
        </div>

        {/* <div className="flex justify-content-center">
          {!showAllProjects ? (
            <button
              className="btn btn-outline-light btn-lg"
              onClick={() => setShowAllProjects(true)}
            >
              <i className="pi pi-eye me-2"></i>
              View All Projects ({projects.length})
            </button>
          ) : (
            <div className="btn-group-projects">
              <button
                className="btn btn-outline-light btn-lg"
                onClick={() => setShowAllProjects(false)}
              >
                <i className="pi pi-arrow-up me-2"></i>Show Featured Only
              </button>
              <button
                className="btn btn-primary btn-lg"
                onClick={() => window.open('https://github.com/know120', '_blank')}
              >
                <i className="pi pi-github me-2"></i>View GitHub Profile
              </button>
            </div>
          )}
        </div> */}
      </section>

      {/* Blog Section */}
      <section id="blog" className="flex flex-column items-center justify-content h-screen bg-blue-500" ref={blogRef}>
        <div className="text-center w-screen">
          <h1 className="section-title text-center mb-4">Latest Insights</h1>
          <div className="">
            <i className="pi pi-file-edit" style={{ fontSize: '4rem', color: '#6366f1', marginBottom: '2rem' }}></i>
            <h3 className="mb-3">Blog Coming Soon!</h3>
            <p className="lead mb-4">Sharing insights about web development, best practices, and latest technologies.</p>
            <div className="upcoming-topics">
              <h4 className="mb-3">Upcoming Topics:</h4>
              <ul className="list-unstyled">
                <li className="mb-2">🚀 Modern React Development Patterns</li>
                <li className="mb-2">⚡ Performance Optimization Techniques</li>
                <li className="mb-2">🎨 Advanced CSS and Animations</li>
                <li className="mb-2">🔧 Full-Stack Development Best Practices</li>
              </ul>
            </div>
            <button className="btn btn-primary btn-lg mt-3">
              <i className="pi pi-bell me-2"></i>Notify Me When Ready
            </button>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="mt-10 h-screen" ref={contactRef}>
        <div className={`container-fluid bg-dark px-0 h-100 d-flex flex-column justify-content-center ${contactInView ? 'animate-in' : ''}`}>
          <ContactForm />

          <div className="text-center mt-3">
            <div className="social-links mb-2">
              {socialLinks.map((link, index) => (
                <a
                  key={index}
                  className="btn btn-outline-light btn-social mx-2 mb-2"
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={link.label}
                >
                  <i className={`pi ${link.icon}`}></i>
                </a>
              ))}
            </div>
            <div className="footer-text text-white">
              <p className="mb-1">
                © {currentYear}{' '}
                <a className="text-white text-decoration-none" href="https://know120.github.io/">
                  Sujay Halder
                </a>
              </p>
              <p className="text-muted small mb-0">Built with React, Tailwind CSS & Modern Web Technologies</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Dashboard;

// src/app/home/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { MenuItem } from 'primeng/api';

@Component({
    selector: 'app-dashboard',
    templateUrl: './dashboard.component.html',
    styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
    
    items!: MenuItem[];

    constructor() { }

    ngOnInit(): void {
        
    }

}

<section id="home" style="padding-top:5rem;">
    <div class="container-fluid">
        <div class="row navigation fixed-top" style="float:center;">
            <div class="col-md-7"></div>
            <div class="col-md-1 col-sm-2 text-center"><a href="#home"><button
                        class="btn btn-outline-light btn-floating m-1">Home</button></a></div>
            <div class="col-md-1 col-sm-2 text-center"><a href="#about"><button
                        class="btn btn-outline-light btn-floating m-1">About</button></a></div>
            <div class="col-md-1 col-sm-2 text-center"><a href="#projects"><button
                        class="btn btn-outline-light btn-floating m-1">Projects</button></a></div>
            <div class="col-md-1 col-sm-2 text-center"><a href="#blog"><button
                        class="btn btn-outline-light btn-floating m-1">Blogs</button></a></div>
            <div class="col-md-1 col-sm-2 text-center"><a href="#contact"><button
                        class="btn btn-outline-light btn-floating m-1">Contact</button></a></div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center" style="margin: auto;">
                <img class="rounded-circle" src="../../../assets/img/me.jpg" alt="image" [width]="300"
                    height="300">
            </div>
            <div class="col text-center float-start" style="font-size:larger; margin: auto;">
                <h1 class="text-center">Hi, I'm Sujay</h1>
                <h2 class="text-center">a Software Engineer</h2>
                <h3 class="text-center">Love to Create</h3>
            </div>
        </div>
    </div>
</section>
<section id="about" style="padding-top:5rem;">
    <h1>Work Experience</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <p-card>
                    <p-header>
                        <h2>Alumnus Software Limited</h2>
                    </p-header>
                    <h3>Full Stack Developer</h3>
                    Developed a web application for one of the leading Tire manufacturing company using Angular 7,
                    Bootstrap 5, .NET Framework, and SQLServer.
                    <p-footer>
                        <h4>July 2022 - Present</h4>
                    </p-footer>
                </p-card>
            </div>
            <div class="col">
                <p-card>
                    <p-header>
                        <h2>Divsoft Software Solutions</h2>
                    </p-header>
                    <h3>Software Engineer</h3>
                    Developed a Over Speed Detection System using CPP and OpenCV. That can receive the speed of the
                    vehicle from a remote server using TCP Connection and Capture the image of vehicle.
                    <p-footer>
                        <h4>August 2021 - July 2022</h4>
                    </p-footer>
                </p-card>
            </div>
        </div>
    </div>

</section>
<section id="projects" style="padding-top:5rem;">
    <h1>Projects</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <p-card>
                    <p-header>
                        <h2>Web Development</h2>
                    </p-header>
                    Developed a web application using Angular 7, Bootstrap 5, HTML5, CSS3, and Typescript.
                    <p-footer>
                        <a href="https://know120.github.io" target="_blank">Visit</a>
                    </p-footer>
                </p-card>
            </div>
            <div class="col">
                <p-card>
                    <p-header>
                        <h2>Data Analysis</h2>
                    </p-header>
                    Analysis and Visualization of data using Python, Pandas, Matplotlib, and Seaborn.
                    <p-footer>
                        <a href="https://jovian.ai/know120/fb-ad-lib" target="_blank">Visit</a>
                    </p-footer>
                </p-card>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p-card>
                    <p-header>
                        <h2>Machine Learing</h2>
                    </p-header>
                    Covid prediction using Machine Learning.
                    <p-footer>
                        <a href="https://know120.github.io" target="_blank">Visit</a>
                    </p-footer>
                </p-card>
            </div>
            <div class="col"></div>
        </div>
    </div>
</section>
<section id="blog" style="padding-top:5rem;">
    <h1>Blogs</h1>
    <p>Coming Soon...</p>

</section>
<section id="contact" style="padding-top:5rem;">
    <footer class="bg-dark text-center text-white">
        <div class="container p-4 pb-0">
            <section class="mb-4">
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/TheSujayHalder"
                    target="_blank" role="button"><i class="pi pi-facebook"></i></a>
                <a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/TheSujayHalder"
                    target="_blank" role="button"><i class="pi pi-twitter"></i></a>
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/the_sujay_halder"
                    target="_blank" role="button"><i class="pi pi-instagram"></i></a>
                <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/sujayhalder"
                    target="_blank" role="button"><i class="pi pi-linkedin"></i></a>
                <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/know120" target="_blank"
                    role="button"><i class="pi pi-github"></i></a>
            </section>
        </div>
        <div class="text-center p-3">
            © 2022:
            <a class="text-white" href="https://know120.github.io/">Sujay Halder</a>
        </div>
    </footer>
</section>
